### ISSUE TITLE
server fails on ubuntu 15.04/vivid

### ISSUE THREAD

**Issue by kirkawolff** [cpoppema/pass-server-node#2]
```
> pass-server-node@0.2.0 start /home/uname/src/pass-server-node-master
> node ./server.js


/home/uname/src/pass-server-node-master/store.js:56
  fs.accessSync(this.passwordDir, fs.R_OK | fs.X_OK)
     ^
TypeError: Object #<Object> has no method 'accessSync'
    at Store.init (/home/uname/src/pass-server-node-master/store.js:56:6)
    at new Store (/home/uname/src/pass-server-node-master/store.js:28:25)
    at Object.<anonymous> (/home/uname/src/pass-server-node-master/store.js:204:18)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/uname/src/pass-server-node-master/views.js:11:13)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)

npm ERR! pass-server-node@0.2.0 start: `node ./server.js`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the pass-server-node@0.2.0 start script.
npm ERR! This is most likely a problem with the pass-server-node package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./server.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls pass-server-node
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.19.0-58-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! cwd /home/uname/src/pass-server-node-master
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/uname/src/pass-server-node-master/npm-debug.log
npm ERR! not ok code 0

```

**Comment by cpoppema** [comment]
Hi @kirkawolff, thanks for trying pass-server-node!

Your stack trace tells me you are using an older version of node.js (0.10.x), most likely the version shipped with Ubuntu. Most Ubuntu and Debian based Linux distributions no longer have up-to-date Node.js versions in their repositories. Node.js 4.x is the LTS version, 0.10.x and 0.12.x are no longer supported (not by me and not by Node.js)
Please refer on how-to install 4.x here: https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions. This will update node as well as npm.

Please try again and let me know if this resolves your issues!

**Comment by kirkawolff** [comment]
The commands 

```
curl -sL https://deb.nodesource.com/setup_4.x | sudo -E bash -
sudo apt-get install -y nodejs
```

did the trick.  Thanks!
